# 6Python高级数据与可视化
# Advanced Data Processing and Visualization of Python
#### Anaconda2 _4.0.0版本
## 6.1聚类分析
* 聚类分析(cluster analysis)
 以相似性为基础把相似的对象通过静态分类的方法分成不同的组别或者更多的子集  
 特性：基于相似性；有多个聚类中心  
* K-MEANS
 K-均值算法表示以空间中k个点为中心进行聚类，对最靠近他们的对象归类

In [2]:
#K-均值算法
#      高数 英语 Python 音乐
#小明  88   64    96    85
#大明  92   99    95   94
#小朋  91   87   99   95
#大朋  78  99    97   81
#小萌  88  78    98   84
#大萌 100  95  100   92
#
from pylab import *
from scipy.cluster.vq import *
list1 = [88.0,74.0,96.0,85.0]
list2 = [92.0,99.0,95.0,94.0]
list3 = [91.0,87.0,99.0,95.0]
list4 = [78.0,99.0,97.0,81.0]
list5 = [88.0,78.0,98.0,84.0]
list6 = [100.0,95.0,100.0,92.0]
data = vstack((list1,list2,list3,list4,list5,list6))
#把六个同学的成绩堆积起来
#http://www.cnblogs.com/harvey888/p/5967352.html
#Python numpy函数hstack() vstack() stack() dstack() vsplit() concatenate()
print data
centroids,_ = kmeans(data,2)
#参数2表示分为两类
result,_= vq(data,centroids)
print result

[[  88.   74.   96.   85.]
 [  92.   99.   95.   94.]
 [  91.   87.   99.   95.]
 [  78.   99.   97.   81.]
 [  88.   78.   98.   84.]
 [ 100.   95.  100.   92.]]
[0 1 1 1 0 1]


##### 下面的程序有问题，没看明白，也无法执行

In [7]:
from matplotlib.finance import quotes_historical_yahoo_ochl
from datetime import date
import pandas as pd
#today1 = date.today()
#end1 = today 
#start = (today.year-1,today.month,today.day)
#去年的今天到今年的今天
start = date(2016,7,1)
end = date(2016,9,30)
listDji = ['AXP', 'BA', 'CAT', 'CSCO', 'CVX', 'DD', 'DIS', 'GE', 'GS', 'HD', 'IBM', 'INTC', 'JNJ',
           'JPM', 'KO', 'MCD', 'MMM', 'MRK', 'MSFT', 'NKE', 'PFE', 'PG', 'T', 'TRV', 'UNH', 'UTX', 'V', 'VZ', 'WMT', 'XOM']
#这有30支股票

quotes = [ [0 for col in range(90)] for row in range(30)]
#获取股票的信息，因为有30支股票，每个股票需要存获取90的信息
#print quotes
listTemp = [ [0 for col in range(90)] for row in range(30)]
#是把股票处理过的相关系数，放在该列表中
#建立一个二维数组 30X90
for i in range(30):
    quotes[i] = quotes_historical_yahoo_ochl(listDji[i],start,end)
#获取30支股票7-9月的信息
#start，end的格式对不对呢？是不是要用Gregorian日历时间格式？---格式可行
#listTemp[i][j] = 1.0 or -1.0 # 1 if the latter is larger than former, otherwise the result is -1
#放的是涨跌系数？？
#这句话没有明白
df = pd.DataFrame(quotes)
#print df  #查看获得的具体数值
days=len(quotes[0])
print days #可用print days查看含义
#days表示有交易数据的天数

##想给获取的数据加上对应的属性fields
#fields = ['date','open','close','high','low','volume']
#quotesdf = pd.DataFrame(quotes, index = quotes[i][0],columns = fields)
#print quotesdf
#AssertionError: 6 columns passed, passed data had 64 columns


for i in range(30):
    for j in range(days-1):
        if(quotes[i][j][2] and quotes[i][j+1][2] and (quotes[i][j+1][2]>=quotes[i][j][2])):
            #参数2表示收盘价所在的位置，具体可以查看week5的相关内容
            #这是一个三维数组
            listTemp[i][j]=1.0
        else:
            listTemp[i][j]=-1.0
data = vstack(listTemp)
#把所有的listTempp[i][j]链接起来
centroids,_ = kmeans(data,4)
result,_= vq(data,centroids)
print result

#把公司和值对应起来
dict_out_put = dict(zip(listDji,result ))
#dict_out_put = dict(zip(result，listDji)) #会出错，因为键只有4个数，只能得到四个结果
print dict_out_put

#对字典进行排序
result_classify = sorted(dict_out_put.iteritems(), key=lambda x: x[1])
print result_classify
#result_classify1 = sorted(dict_out_put, key=lambda x: x[1])
#一定要用.iteritems()，这样才是一个个值从字典中取出来的，才会有想获取的x[0],x[1]存在
#print result_classify1  #IndexError: string index out of range

#把排序好的公司提取出来


64
[0 0 0 0 2 0 2 0 2 0 0 0 1 2 1 1 0 1 0 0 1 1 3 2 1 0 0 3 3 2]
{'AXP': 0, 'BA': 0, 'CVX': 2, 'CSCO': 0, 'DD': 0, 'V': 0, 'CAT': 0, 'VZ': 3, 'MSFT': 0, 'IBM': 0, 'PG': 1, 'DIS': 2, 'HD': 0, 'GS': 2, 'INTC': 0, 'WMT': 3, 'GE': 0, 'T': 3, 'MRK': 1, 'UNH': 1, 'JPM': 2, 'UTX': 0, 'XOM': 2, 'TRV': 2, 'PFE': 1, 'NKE': 0, 'MCD': 1, 'KO': 1, 'MMM': 0, 'JNJ': 1}
[('AXP', 0), ('BA', 0), ('CSCO', 0), ('DD', 0), ('V', 0), ('CAT', 0), ('MSFT', 0), ('IBM', 0), ('HD', 0), ('INTC', 0), ('GE', 0), ('UTX', 0), ('NKE', 0), ('MMM', 0), ('PG', 1), ('MRK', 1), ('UNH', 1), ('PFE', 1), ('MCD', 1), ('KO', 1), ('JNJ', 1), ('CVX', 2), ('DIS', 2), ('GS', 2), ('JPM', 2), ('XOM', 2), ('TRV', 2), ('VZ', 3), ('WMT', 3), ('T', 3)]


In [39]:
#列表排序
list1 = ['AXP','CVX','DIS','JNJ','MCD','UTX','WMT','XOM','GE','GS','JPM','MMM','NKE','PFE','TRV','V','CSCO',
        'IBM','INTC','KO','MRK','MSFT','T','VZ','BA','CAT','DD','HD','PG','UNH']
#这些公司是否现在还存在？  最好是自己从网上挖掘出30个公司的信息
b1 = sorted(list1)
print b1
#含有元组的列表排序
list2 = [('b',2),('c',1),('a',0)]
b1 = sorted(list2,key=lambda a_tuple: a_tuple[0])
print b1
b2 = sorted(list2,key=lambda a_tuple: a_tuple[1])
print b2
b2_reverse = sorted(list2,key=lambda a_tuple: a_tuple[1],reverse=1)
#逆序排序
print b2_reverse
b2_cmp = sorted(list2,cmp=lambda x,y: cmp(x[1],y[1]))
print b2_cmp

['AXP', 'BA', 'CAT', 'CSCO', 'CVX', 'DD', 'DIS', 'GE', 'GS', 'HD', 'IBM', 'INTC', 'JNJ', 'JPM', 'KO', 'MCD', 'MMM', 'MRK', 'MSFT', 'NKE', 'PFE', 'PG', 'T', 'TRV', 'UNH', 'UTX', 'V', 'VZ', 'WMT', 'XOM']
[('a', 0), ('b', 2), ('c', 1)]
[('a', 0), ('c', 1), ('b', 2)]
[('b', 2), ('c', 1), ('a', 0)]
[('a', 0), ('c', 1), ('b', 2)]


In [ ]:
#对字典进行排序
#http://www.cnblogs.com/kaituorensheng/archive/2012/08/07/2627386.html


### 6.2Matplotlib绘图
* Matplotlib绘图 （http://matplotlib.org/)      
  1.最著名Python绘图库，主要用于二维绘图：画图质量高；方便快捷的绘图模块     
  2.绘图API——pyplot模块  
  3.集成库——pylab模块（包含NumPy和pyplot中的常用函数）  

In [28]:
#将可口可乐公司近一年来股票收盘价的月平均价绘制成折线图
import time
from datetime import date
from matplotlib.finance import quotes_historical_yahoo_ochl
from datetime import datetime
import pandas as pd
import matplotlib.pyplot as plt

today=date.today()    
start=(today.year-1,today.month,today.day)  #获取去年的年、月、日
quotes=quotes_historical_yahoo_ochl('KO',start,today)  #查询可口可乐公司历史数据
#这个是matplotlib.finance专门对针对Yahoo财经开发的包
#print len(quotes)   #存在历史数据的天数
fields=['date','open','close','high','low','volumn']

listDate=[]
for i in range(0,len(quotes)):
    x=date.fromordinal(int(quotes[i][0]))      #将Gregorian日历时间转换为date对象
    y=datetime.strftime(x,'%Y-%m-%d')    #将datetime对象转化为字符串格式
    listDate.append(y)
#print listDate
quoteskodf=pd.DataFrame(quotes,index=listDate,columns=fields) #添加列名，更改索引
quoteskodf.drop(['date'],axis=1)     #去除date列
#print quoteskodf.drop(['date'],axis=1)
#print quoteskodf   #为什么这么打印出来date还在呢？
listtemp=[]  #初始化列表
for i in range(0,len(quoteskodf)):
    temp=time.strptime(quoteskodf.index[i],'%Y-%m-%d')  #quoteskodf.index[i]返回索引日期,如‘2016-05-14’，转化为元组
    #print temp  
    #time.struct_time(tm_year=2016, tm_mon=10, tm_mday=10, tm_hour=0, tm_min=0, tm_sec=0, tm_wday=0, tm_yday=284, tm_isdst=-1)
    listtemp.append(temp.tm_mon) #把月份放入listtemp列表中去
    
#print listtemp
#print len(listtemp) 
tempkodf=quoteskodf.copy()       #拷贝一份数据到tempkodf
tempkodf['month']=listtemp       #新增month列
closemeansko=tempkodf.groupby('month').mean().close  #求每月收盘价均值,close表示columns的值close
#这个计算存在缺陷，如果是存在跨年则会把头和尾给和在一起计算，因为按照month分组都是同一个值
print closemeansko

listko=[]
for i in range(1,13):   #range(x,y)是指从x起到y-1结束
    listko.append(closemeansko[i])  #返回第i行的值
listkoindex=closemeansko.index   #listkoindex返回索引，即月份1、2、3、4..
print listkoindex
plt.plot(listkoindex,listko)   #输出折线图
plt.plot(listkoindex,listko,'g*')   #输出*散点图
#plt.show()

month
1     40.886590
2     41.809551
3     43.958528
4     44.621046
5     43.818324
6     44.112337
7     44.442122
8     42.965381
9     42.203695
10    41.627600
11    41.208241
12    41.345714
Name: close, dtype: float64
Int64Index([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12], dtype='int64', name=u'month')


### matplotlib的基本用法
* 子图：  
  1.subplots: 在同一个画布中绘制多个小图，subplot(231)新建一个2X3个小图，选择1号小图    
  2.axes： 同一个图中多个图重叠，axes([left,bottom,width,height])参数范围为(0,1)  
  

In [61]:
#利用numpy产生数字
import numpy as np
import matplotlib.pyplot as plt
x = np.arange(0.,4.,0.1) #产生一维数组，步长为0.1，最大值不超过4.0
#print x
y = np.arange(0.,4.,0.1)
#plt.plot(x,x+3,x**2)
# ValueError: third arg must be a format string
#需要画几个函数的图形，就需要在函数式前声明变量几次
#plt.plot(x,x,x,x+2,x,x**2)   
plt.plot(x,x,x,x**3,x+3,x**2)
# #plot后不仅能跟列表，也能接数组
#plt.show()
z1=x+y
z2 = 10*x+y
plt.plot(z1)
plt.plot(z2)
plt.show()
#http://matplotlib.org/api/pyplot_api.html#matplotlib.pyplot.plot
#help(plt.plot) #查看函数的用法


In [63]:
import pylab as pl
import numpy as np
pl.figure(figsize=(8,6),dpi=100)
t=np.arange(0.,4.,0.1)
pl.plot(t,t,color='red',linestyle='-',linewidth=3,label='Line 1')
#plt.show()
pl.plot(t,t+2,color='green',linestyle='',marker='*',linewidth=3,label='Line 2')
pl.plot(t,t**2,color='blue',linestyle='',marker='+',linewidth=3,label='Line 3')
pl.legend(loc='upper left')
plt.show()

### pandas绘图

In [68]:
plt.plot(closemeansko)
plt.title('Stock Statistics of Coca-Cola')
plt.xlabel('Month')
plt.ylabel('Average Close Price')
plt.show()

import pandas as pd
closemeansko.plot()
plt.title('Stock Statistics of Coca-Cola')
plt.xlabel('Month')
plt.ylabel('Average Close Price')
plt.show()

In [80]:
#pandas作图
import pandas as pd
from datetime import date
from matplotlib.finance import quotes_historical_yahoo_ochl
#import matplotlib.pyplot as plt

start=(2014,10,1)
end=(2014,10,31)
quotes=quotes_historical_yahoo_ochl('IBM',start,end)
quotesINTC=quotes_historical_yahoo_ochl('INTC',start,end)
quotesGE=quotes_historical_yahoo_ochl('GE',start,end)
fields=['date','open','close','high','low','volume']
#将索引换成时间，http://www.cnblogs.com/lhj588/archive/2012/04/23/2466653.html
list1=[]
for i in range(0,len(quotesINTC)):
    x=date.fromordinal(int(quotesINTC[i][0]))      #将Gregorian日历时间转换为date对象。若写成datetime.fromordinal，则返回datetime对象
    y=date.strftime(x,'%Y-%m-%d')
    list1.append(y)
    
list2=[]
for i in range(0,len(quotesGE)):
    x=date.fromordinal(int(quotesGE[i][0]))
    y=date.strftime(x,'%Y-%m-%d')
    list2.append(y)
    
quotesdfINTC=pd.DataFrame(quotesINTC,index=list1,columns=fields)
quotesdfINTC=quotesdfINTC.drop(['date'],axis=1)
quotesdfGE=pd.DataFrame(quotesGE,index=list1,columns=fields)
quotesdfGE=quotesdfGE.drop(['date'],axis=1)

quotesdf=pd.DataFrame()
quotesdf['closeINTC']=cc=quotesdfINTC.close
quotesdf['closeGE']=dd=quotesdfGE.close
#quotesdf.plot(kind='bar')   #画图，kind有很多可以选择
#quotesdf.plot(kind='kde')  #kind='kde'概率分布图
quotesdf.plot(kind='scatter',x='closeINTC',color='g',y='closeGE')
plt.show()
cc.plot(color='r',marker='D',label='Intel')
dd.plot(color='g',marker='D',label='GE')
plt.legend(loc='best')
#quotesdf.to_csv(u'输出csv格式.csv')           #汉字前不加u会出现乱码形式。csv（逗号分隔值）文件用记事本打开会发现数值间以逗号相隔，以此得名
#result_read =  pd.read_csv('输出csv格式.csv') #读csv文件
#print result_read['2']  #读取文件中具体某一列，2是指默认生成的columns的值
#quotesdf.to_excel(u'输出excel格式.xls')  #还有read_excel()

In [82]:
#古腾堡项目
#计算NTLK中目前收录的古滕堡项目的书
#from nltk.corpus import gutenberg
#print gutenberg.fileids()